### ISSUE TITLE
Improved task error handling on dashboard 

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1250]
Right now, when a upload task fails on the dashboard it shows as successful in the task bar. A user only knows there's been a problem when they go to the asset detail page and see that it's failed. There is no error messaging on this page. 

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/2179b500-a327-404e-87e0-a04ce6413e43)

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/9b21a352-5533-4ecb-ae32-4c9ff7f1e7fa)

This was surfaced in a friction log by @ecmulli and has come up in conversations with users

**Comment by adamsoffer** [comment]
Hey @pglowacky - can you post that link of the status error codes you shared with me? I believe it was in a spreadsheet.

**Comment by pglowacky** [comment]
https://docs.google.com/spreadsheets/d/1i9o8B3HpuWvFzRRDwIjiSXU1ghmvX2OTIFSZ5wLyLII/edit#gid=0

@gioelecerati Is this spreadsheet up to date?

**Comment by gioelecerati** [comment]
> https://docs.google.com/spreadsheets/d/1i9o8B3HpuWvFzRRDwIjiSXU1ghmvX2OTIFSZ5wLyLII/edit#gid=0
> 
> @gioelecerati Is this spreadsheet up to date?

It was still at the recommended errors, just updated it with the existing error messages
[Reference in case](https://github.com/livepeer/task-runner/pull/61/files)

**Comment by victorges** [comment]
Could show asset progress as well during `processing` phase (`asset.status.phase`) from `asset.status.progress`

**Comment by clacladev** [comment]
@adamsoffer Can you please recap what are the actual changes you want to perform to this screen?

**Comment by adamsoffer** [comment]
Hey @clacladev - [here's](https://www.figma.com/file/o0lkaZxamhUfG6eqSglhPO/Livepeer-Studio-Dashboard?node-id=799%3A4280) the updated design for error handling during upload and a list of tasks I've determined we need to complete to close out this issue. Let me know if this makes sense or I'm missing anything.

### Tasks
- [ ] Add error message from the api response to the snackbar component & table row component if an upload failed during processing
- [ ] Add ability to delete asset that failed to get processed (users should only be able to delete assets that failed to get processed)
- [ ] Prevent users from uploading unsupported file formats by restricting input types on the upload component.


### Design preview

![Asset - Upload failed](https://user-images.githubusercontent.com/555740/191886948-7b9352e2-e4be-4435-ae4b-1cbd20c55a6a.png)
